// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Utilisé par la CLI (migrate, generate, studio) : pooler session-mode, pas le pooler
    // transaction-mode (DATABASE_URL) que l'application utilise à l'exécution (src/lib/db.ts).
    url: process.env["DIRECT_URL"],
  },
});
